# - name: Install Kea DHCP packages
#   become: true
#   ansible.builtin.apt:
#     name:
#       - "{{ kea_dhcp_package_name }}"
#       - kea-common
#     state: present
#     update_cache: true
#   when: kea_dhcp4_enabled | bool

- name: Ensure Kea configuration directory exists
  become: true
  ansible.builtin.file:
    path: "{{ kea_dhcp_config_dir }}"
    state: directory
    mode: "0750"

- name: Ensure Kea log directory exists
  become: true
  ansible.builtin.file:
    path: "{{ kea_dhcp_log_dir }}"
    state: directory
    mode: "0750"
    owner: "_kea"
    group: "_kea"

- name: Generate Kea DHCP4 configuration from YAML
  become: true
  ansible.builtin.copy:
    content: "{{ kea_dhcp_config | to_nice_json }}"
    dest: "{{ kea_dhcp_config_file }}"
    mode: "0644"
    owner: "_kea"
    group: "_kea"
  notify: Restart Kea DHCP

- name: Validate Kea configuration
  become: true
  become_user: _kea
  ansible.builtin.command:
    cmd: "kea-dhcp4 -t {{ kea_dhcp_config_file }}"
  register: kea_validate_result
  changed_when: false
  failed_when: kea_validate_result.rc != 0

- name: Ensure Kea DHCP service is enabled and started
  become: true
  ansible.builtin.service:
    name: "{{ kea_dhcp_service_name }}"
    enabled: true
    state: started

